# Generated by Django 4.2.7 on 2023-11-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketmaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.CharField(max_length=200, verbose_name='Event Name')),
                ('name', models.CharField(max_length=200, verbose_name='Event Name')),
                ('venue', models.CharField(max_length=200, verbose_name='Venue Name')),
                ('address', models.CharField(max_length=150, verbose_name='Venue Address')),
                ('city', models.CharField(max_length=150, verbose_name='Event City')),
                ('state', models.CharField(max_length=100, verbose_name='Event State')),
                ('start_date', models.CharField(max_length=100, verbose_name='Event Date')),
                ('start_time', models.CharField(max_length=100, verbose_name='Event Time')),
                ('ticket_link', models.URLField(verbose_name='Ticket Link')),
                ('image_url', models.URLField(verbose_name='Image URL')),
            ],
        ),
    ]
