# Generated by Django 4.2.7 on 2023-12-08 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketmaster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventhistory',
            name='user',
        ),
    ]
