# Generated by Django 4.2.7 on 2023-12-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketmaster', '0002_alter_notehistory_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notehistory',
            name='notes',
            field=models.TextField(),
        ),
    ]
