# Generated by Django 4.2 on 2023-12-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketmaster', '0002_eventfavorite_eventhistory_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='Ticketmaster.eventfavorite'),
        ),
    ]
