# Generated by Django 4.2.7 on 2023-12-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketmaster', '0003_alter_notehistory_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notehistory',
            old_name='notes',
            new_name='message',
        ),
    ]
