# Generated by Django 4.2.7 on 2023-12-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketmaster', '0004_rename_notes_notehistory_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfavorite',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
